source 'http://rubygems.org'
gem 'jekyll'
gem 'rake'
gem 'puma'
gem 'rouge'
gem 'rack-contrib'
gem 'rack-rewrite'
gem 'jekyll-scholar', :git =>'https://github.com/apanda/jekyll-scholar.git', :branch => 'master', :tag => 'sep29'
gem 'jekyll-paginate'
gem 'jekyll-assets'
